Add chocolatey install method
AqoviaCookbooks/nodejs pull request #1
Opened 2019-04-23 10:44 UTC by margani

### Description

Adds a new install method which installs the LTS version of NodeJS using [Chocolatey](https://chocolatey.org/packages/nodejs-lts).

### Issues Resolved

With this install method, we can install NodeJS for windows too.

### Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

2019-04-23 13:34 UTC, jj-aqovia approved these changes

2019-04-23 13:52 UTC, ma499 reviewed
_[Duplicated below](https://github.com/AqoviaCookbooks/nodejs/pull/1#pullrequestreview-229565481)._

2019-04-23 13:53 UTC, ma499 requested changes
As discussed.
1. Change default attributes so that chocolatey is selected package source when running on Windows.
2. Update Readme.md
3. Update 'version' and 'supports' (OS) in metadata and changelog -> 6.1
4. Update Test Kitchen.
5. Link to upstream PR and link upstream PR to Taliesin's old one.

2019-04-23 14:18 UTC, margani commented
[Upstream PR](https://github.com/redguide/nodejs/pull/200)

2019-04-25 10:41 UTC, ma499 approved these changes

2019-04-25 10:41 UTC, merged